### ISSUE TITLE
Add default dict?

### ISSUE THREAD

**Issue by tommy-mor** [Belkworks/quick#1]
Very useful IMO. Love your library 

https://stackoverflow.com/questions/10371155/is-there-a-pythons-defaultdict-functionality-available-in-lua

**Comment by tommy-mor** [comment]
Or also maybe something like “sep”.join([“a”,”b”,”c”]) ==> “asepbsepc” from python

**Comment by safazi** [comment]
@tommy-mor default dict is a great idea!
I'll get started on that.

Answering your second comment, you can currently join an array with `_.join(array, sep) -> string`.
In your example, it'd be:
```lua
_.join({'a', 'b', 'c'}, "sep") -- "asepbsepc"
```

**Comment by safazi** [comment]
@tommy-mor `_.defaultdict` implemented, see documentation for usage

**Comment by tommy-mor** [comment]
amazing, thank you so much
